"""add health_steps_intraday table

Revision ID: ad48f5829c07
Revises: da1a7a9cf8ac
Create Date: 2026-01-08 22:18:26.085979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad48f5829c07'
down_revision: Union[str, None] = 'da1a7a9cf8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_steps_intraday',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID that the health_steps belongs'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Health steps timestamp (datetime)'),
    sa.Column('steps', sa.Integer(), nullable=False, comment='Number of steps taken'),
    sa.Column('source', sa.String(length=250), nullable=True, comment='Source of the health steps data'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_steps_intraday_user_id'), 'health_steps_intraday', ['user_id'], unique=False)
    op.alter_column('server_settings', 'units',
               existing_type=sa.INTEGER(),
               comment='Units (1=metric, 2=imperial)',
               existing_comment='Units (one digit)(1 - metric, 2 - imperial)',
               existing_nullable=False)
    op.alter_column('server_settings', 'public_shareable_links',
               existing_type=sa.BOOLEAN(),
               comment='Allow public shareable links',
               existing_comment='Allow public shareable links (true - yes, false - no)',
               existing_nullable=False)
    op.alter_column('server_settings', 'public_shareable_links_user_info',
               existing_type=sa.BOOLEAN(),
               comment='Show user info on public links',
               existing_comment='Allow show user info on public shareable links (true - yes, false - no)',
               existing_nullable=False)
    op.alter_column('server_settings', 'login_photo_set',
               existing_type=sa.BOOLEAN(),
               comment='Login photo has been set',
               existing_comment='Is login photo set (true - yes, false - no)',
               existing_nullable=False)
    op.alter_column('server_settings', 'currency',
               existing_type=sa.INTEGER(),
               comment='Currency (1=euro, 2=dollar, 3=pound)',
               existing_comment='Currency (one digit)(1 - euro, 2 - dollar, 3 - pound)',
               existing_nullable=False)
    op.alter_column('server_settings', 'num_records_per_page',
               existing_type=sa.INTEGER(),
               comment='Records per page in lists',
               existing_comment='Number of records per page in lists',
               existing_nullable=False)
    op.alter_column('server_settings', 'signup_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Allow user registration',
               existing_comment='Allow user sign-up registration (true - yes, false - no)',
               existing_nullable=False)
    op.alter_column('server_settings', 'signup_require_admin_approval',
               existing_type=sa.BOOLEAN(),
               comment='Require admin approval for signups',
               existing_comment='Require admin approval for new sign-ups (true - yes, false - no)',
               existing_nullable=False)
    op.alter_column('server_settings', 'signup_require_email_verification',
               existing_type=sa.BOOLEAN(),
               comment='Require email verification for signups',
               existing_comment='Require email verification for new sign-ups (true - yes, false - no)',
               existing_nullable=False)
    op.alter_column('server_settings', 'sso_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Enable SSO/IdP login',
               existing_comment='Enable SSO/IdP login (true - yes, false - no)',
               existing_nullable=False)
    op.alter_column('server_settings', 'local_login_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Allow local username/password login',
               existing_comment='Allow local username/password login (true - yes, false - no)',
               existing_nullable=False)
    op.alter_column('server_settings', 'sso_auto_redirect',
               existing_type=sa.BOOLEAN(),
               comment='Auto-redirect to SSO if only one IdP',
               existing_comment='Auto-redirect to SSO if only one IdP (true - yes, false - no)',
               existing_nullable=False)
    op.alter_column('server_settings', 'tileserver_url',
               existing_type=sa.VARCHAR(),
               comment='Map tile server URL template',
               existing_comment='URL template for the map tileserver',
               existing_nullable=False)
    op.alter_column('server_settings', 'tileserver_attribution',
               existing_type=sa.VARCHAR(),
               comment='Map tile attribution',
               existing_comment='Attribution string for the map tileserver',
               existing_nullable=False)
    op.alter_column('server_settings', 'map_background_color',
               existing_type=sa.VARCHAR(),
               comment='Map background hex color',
               existing_comment='Background color for the map',
               existing_nullable=False)
    op.alter_column('server_settings', 'password_type',
               existing_type=sa.VARCHAR(),
               comment='Password policy (strict, length_only)',
               existing_comment='Password type policy (strict, length_only)',
               existing_nullable=False)
    op.alter_column('server_settings', 'password_length_regular_users',
               existing_type=sa.INTEGER(),
               comment='Min password length for regular users',
               existing_comment='Minimum password length for regular users',
               existing_nullable=False)
    op.alter_column('server_settings', 'password_length_admin_users',
               existing_type=sa.INTEGER(),
               comment='Min password length for admin users',
               existing_comment='Minimum password length for admin users',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_settings', 'password_length_admin_users',
               existing_type=sa.INTEGER(),
               comment='Minimum password length for admin users',
               existing_comment='Min password length for admin users',
               existing_nullable=False)
    op.alter_column('server_settings', 'password_length_regular_users',
               existing_type=sa.INTEGER(),
               comment='Minimum password length for regular users',
               existing_comment='Min password length for regular users',
               existing_nullable=False)
    op.alter_column('server_settings', 'password_type',
               existing_type=sa.VARCHAR(),
               comment='Password type policy (strict, length_only)',
               existing_comment='Password policy (strict, length_only)',
               existing_nullable=False)
    op.alter_column('server_settings', 'map_background_color',
               existing_type=sa.VARCHAR(),
               comment='Background color for the map',
               existing_comment='Map background hex color',
               existing_nullable=False)
    op.alter_column('server_settings', 'tileserver_attribution',
               existing_type=sa.VARCHAR(),
               comment='Attribution string for the map tileserver',
               existing_comment='Map tile attribution',
               existing_nullable=False)
    op.alter_column('server_settings', 'tileserver_url',
               existing_type=sa.VARCHAR(),
               comment='URL template for the map tileserver',
               existing_comment='Map tile server URL template',
               existing_nullable=False)
    op.alter_column('server_settings', 'sso_auto_redirect',
               existing_type=sa.BOOLEAN(),
               comment='Auto-redirect to SSO if only one IdP (true - yes, false - no)',
               existing_comment='Auto-redirect to SSO if only one IdP',
               existing_nullable=False)
    op.alter_column('server_settings', 'local_login_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Allow local username/password login (true - yes, false - no)',
               existing_comment='Allow local username/password login',
               existing_nullable=False)
    op.alter_column('server_settings', 'sso_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Enable SSO/IdP login (true - yes, false - no)',
               existing_comment='Enable SSO/IdP login',
               existing_nullable=False)
    op.alter_column('server_settings', 'signup_require_email_verification',
               existing_type=sa.BOOLEAN(),
               comment='Require email verification for new sign-ups (true - yes, false - no)',
               existing_comment='Require email verification for signups',
               existing_nullable=False)
    op.alter_column('server_settings', 'signup_require_admin_approval',
               existing_type=sa.BOOLEAN(),
               comment='Require admin approval for new sign-ups (true - yes, false - no)',
               existing_comment='Require admin approval for signups',
               existing_nullable=False)
    op.alter_column('server_settings', 'signup_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Allow user sign-up registration (true - yes, false - no)',
               existing_comment='Allow user registration',
               existing_nullable=False)
    op.alter_column('server_settings', 'num_records_per_page',
               existing_type=sa.INTEGER(),
               comment='Number of records per page in lists',
               existing_comment='Records per page in lists',
               existing_nullable=False)
    op.alter_column('server_settings', 'currency',
               existing_type=sa.INTEGER(),
               comment='Currency (one digit)(1 - euro, 2 - dollar, 3 - pound)',
               existing_comment='Currency (1=euro, 2=dollar, 3=pound)',
               existing_nullable=False)
    op.alter_column('server_settings', 'login_photo_set',
               existing_type=sa.BOOLEAN(),
               comment='Is login photo set (true - yes, false - no)',
               existing_comment='Login photo has been set',
               existing_nullable=False)
    op.alter_column('server_settings', 'public_shareable_links_user_info',
               existing_type=sa.BOOLEAN(),
               comment='Allow show user info on public shareable links (true - yes, false - no)',
               existing_comment='Show user info on public links',
               existing_nullable=False)
    op.alter_column('server_settings', 'public_shareable_links',
               existing_type=sa.BOOLEAN(),
               comment='Allow public shareable links (true - yes, false - no)',
               existing_comment='Allow public shareable links',
               existing_nullable=False)
    op.alter_column('server_settings', 'units',
               existing_type=sa.INTEGER(),
               comment='Units (one digit)(1 - metric, 2 - imperial)',
               existing_comment='Units (1=metric, 2=imperial)',
               existing_nullable=False)
    op.drop_index(op.f('ix_health_steps_intraday_user_id'), table_name='health_steps_intraday')
    op.drop_table('health_steps_intraday')
    # ### end Alembic commands ###
